Increase streaming frame size
Have observed errors like this when streaming with google search enabled:
io.cequence.wsclient.domain.CequenceWSException: PlayWSStreamClientEngineImpl.models/gemini-2.5-flash:streamGenerateContent: Stream framing problem occurred. Read 20173 bytes which is more than 20000 without seeing a line terminator.